# devops/monitoring/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'nodejs'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:5000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus:9090

  - job_name: 'blockchain'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['blockchain-node:8545']
    params:
      module: [eth]

  - job_name: 'frontend'
    metrics_path: '/_next/static/__webpack_metrics__'
    static_configs:
      - targets: ['frontend:80']