# .github/workflows/full-pipeline.yml
name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scanning:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: SAST with Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: p/owasp-top-ten
    
    - name: SCA with Snyk
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    
    - name: Container Scanning
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/${{ github.repository }}'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
  build-deploy:
    needs: security-scanning
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - name: Build and Push Container
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
        sbom: true
        provenance: true
    
    - name: Deploy to Kubernetes
      uses: steebchen/kubectl@v2
      with:
        command: apply -f devops/infrastructure/kubernetes/production
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}